apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content  # Name of the volume to mount
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-content    # Name of the volume defined
        configMap:
          name: web-content-configmap  # Name of the ConfigMap containing your files
